services:
  app:
    container_name: app-container
    image: app-soft
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data.txt:/data.txt

volumes:
  app:
